---
# tasks file for roles/setup/fail2ban

- name: Update_apt_cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install rsyslog
  ansible.builtin.apt:
    name: rsyslog
    state: present

- name: Install iptables
  ansible.builtin.apt:
    name: iptables
    state: present

- name: Ensure the log directory exists
  ansible.builtin.file:
    path: /var/log/sshd/
    state: directory
    mode: '0755'

- name: Create SSH log file
  ansible.builtin.file:
    path: /var/log/sshd/sshd.log
    state: touch
    owner: sshd
    group: adm
    mode: '0640'

- name: Configure rsyslog for SSH logging
  ansible.builtin.copy:
    dest: /etc/rsyslog.d/50-ssh.conf
    content: |
      if $programname == 'sshd' then /var/log/sshd/sshd.log
      & stop
    owner: root
    group: root
    mode: '0644'

- name: Restart rsyslog service
  ansible.builtin.systemd:
    name: rsyslog
    state: restarted

- name: Enable log sshd
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#SyslogFacility AUTH'
    line: 'SyslogFacility AUTH'
    state: present

- name: Level log sshd
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#LogLevel INFO'
    line: 'LogLevel INFO'
    state: present

# fail2ban
- name: Install Fail2Ban
  ansible.builtin.apt:
    name: fail2ban
    state: present

- name: Restart sshd service to apply changes
  ansible.builtin.systemd:
    name: sshd
    state: restarted

- name: Config fail2ban
  ansible.builtin.template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart_service

- name: Start and autostart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: true

# test
- name: Pause
  ansible.builtin.pause:
    seconds: 3
  tags: test

- name: Check service status
  ansible.builtin.service:
    name: fail2ban
    state: started
  register: service_status
  tags: test

- name: Info
  ansible.builtin.assert:
    that:
      - service_status.status.ActiveState == 'active'
    fail_msg: "[error] - Служба не запущена"
    success_msg: "[info] - Служба запущена"
