---
# tasks file for roles/setup/ufw
- name: Ensure UFW is installed
  ansible.builtin.apt:
    name: ufw
    state: present
  become: true

- name: Set default outgoing policy to allow
  community.general.ufw:
    default: allow
    direction: outgoing
  become: true

- name: Allow SSH connections
  community.general.ufw:
    rule: allow
    port: 22
    proto: tcp
  become: true

- name: Ensure UFW is enabled and set to start on boot
  community.general.ufw:
    state: enabled
  become: true
